sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

# Si este script falla se debe a que se cambio la raiz o el nombre del proyecto en el dockerfile
script:
  - docker exec -it djangofull /bin/bash -c "source /opt/venv/bin/activate && ./manage.py test"

after_script:
  - docker-compose down
