version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: djangofull-redis

  db:
    build: ./postgres
    container_name: djangofull-db
    restart: always
    tty: true
    ports:
      - 5432:5432
      - 24:22

  neo4j:
    build: ./neo4j
    container_name: djangofull-neo4j
    restart: always
    tty: true
    volumes:
      - ./project/neo4j:/data  # base de datos persistente
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687
      - 25:22

  vue:
    build: ./vue
    container_name: djangofull-vue
    ports:
      - 80:80

  web:
    build: ./project
    container_name: djangofull
    restart: always
    tty: true
    depends_on:
      - redis
      - db
      - neo4j
      - vue
    ports:
      - 23:22
      - 8000:80
      - 8001:8080
      - 5000:5000
      - 5050:5555
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
