version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: djangofull-redis

  db:
    build: ./postgres
    container_name: djangofull-db
    restart: always
    tty: true
    ports:
      - 5432:5432
      - 32:22

  neo4j:
    build: ./neo4j
    # image: neo4j:4.0.1
    container_name: djangofull-neo4j
    restart: always
    tty: true
    volumes:
      - ./project/neo4j:/data  # base de datos persistente
    # environment:
      # - NEO4J_AUTH=neo4j/password
      # - SECURE_FILE_PERMISSIONS=yes  # verificación estricta de permisos de archivo
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687
      - 87:22

  vue: # Needed config ansible vue
    build: ./vue
    container_name: djangofull-vue
    # tty: true
    ports:
      - 80:80

  web: # Needed config ansible NGNIX
    build: ./project
    container_name: djangofull
    restart: always
    depends_on:
      - redis
      - db
    volumes:
      - ./project:/var/www/project
      - ./scripts:/opt/scripts
    ports:
      - 22:22
      - 8000:80
      - 5000:8080
      - 5050:5555
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: bash /opt/scripts/run.sh
    tty: true
