version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: djfullapp-redis

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
      target: base-develop
    container_name: djfullapp-db
    restart: always
    tty: true
#    volumes:
#      - postgres:/var/lib/postgresql/11/main  # base de datos persistente
    ports:
      - 5432:5432
      - 24:22

  neo4j:
    build:
      context: ./neo4j
      dockerfile: Dockerfile
      target: base-develop
    container_name: djfullapp-neo4j
    restart: always
    tty: true
#    volumes:
#      - neo4j:/data  # base de datos persistente
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687
      - 25:22

  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
      target: base-develop
    container_name: djfullapp-vue
    deploy:
      resources:
        limits:
            cpus: '0.50'
            memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
#    volumes:
#      - ./vue/djfullapp-vue:/app/vue
#      - /app/node_modules
    ports:
      - 80:80

  web:
    build:
      context: ./django
      dockerfile: Dockerfile
      target: base-develop
    container_name: djfullapp
    restart: always
    tty: true
    depends_on:
      - redis
      - db
      - neo4j
      - vue
#    volumes:
#      - ./django:/webapps/django
#      - ./django/ansible:/tmp/ansible
    ports:
      - 7000:80
      - 7001:8080
      - 7002:5555
      - 23:22
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: >
      sh -c "service supervisor start &&
             supervisorctl reread &&
             supervisorctl update &&
             supervisorctl start all &&
             service ssh start &&
             service nginx start &&
             wait-for-it db:5432 --strict --timeout=60 -- django-migrate &&
             /bin/bash"

#volumes:
#  postgres:
#    driver: local-persist
#    driver_opts:
#      mountpoint: ${PWD}/data/postgres
#  neo4j:
#    driver: local-persist
#    driver_opts:
#      mountpoint: ${PWD}/data/neo4j
